### ISSUE TITLE
Invalid hostname error while running bootstrap-vitasdk.sh

### ISSUE THREAD

**Issue by MaskedFuyu** [vitasdk/vdpm#62]
Trying to install on macOS 11.0 beta.

The script failed and the output:
```
sudo ./bootstrap-vitasdk.sh
==> Installing vitasdk to /usr/local/vitasdk
http://: invalid hostname.
Please add the following to the bottom of your .bashrc:
export VITASDK=/usr/local/vitasdk
export PATH=$VITASDK/bin:$PATH
and then restart your terminal
```
No additional error information output so I'm not sure what had caused this.

**Comment by yne** [comment]
can you try to execute the following line : 
```bash
wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python - $@
```

and post the output

**Comment by MaskedFuyu** [comment]
Nothing output. $? is 0.

**Comment by yne** [comment]
can you try `python --version` ?
also, does `wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py` output the python code ?

can we replace all those python code + github API + Travis API with a simpler line that only rely on standard UNIX utilities :
```sh
URL=https://github.com/vitasdk/autobuilds/releases
wget -qO- $URL | grep -Po "/download/.*.tar.bz2" | sed s,^,$URL, | grep osx
```

**Comment by JoseOcasio** [comment]
I have the same issue. This is the output when running that command
```
`wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python - $@

Traceback (most recent call last):
  File "<stdin>", line 80, in <module>
  File "<stdin>", line 67, in last_built_toolchain
  File "<stdin>", line 43, in fetch_succeeded_tags
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>
`
```

**Comment by JoseOcasio** [comment]
And yes, `URL=https://github.com/vitasdk/autobuilds/releases
wget -qO- $URL | grep -Po "/download/.*.tar.bz2" | sed s,^,$URL, | grep osx` returns the python code

**Comment by MaskedFuyu** [comment]
> can you try `python --version` ?
> also, does `wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py` output the python code ?
> 
> can we replace all those python code + github API + Travis API with a simpler line that only rely on standard UNIX utilities :
> 
> ```shell
> URL=https://github.com/vitasdk/autobuilds/releases
> wget -qO- $URL | grep -Po "/download/.*.tar.bz2" | sed s,^,$URL, | grep osx
> ```

My python version is 2.7.16.

`wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py` output the python code


```
URL=https://github.com/vitasdk/autobuilds/releases
wget -qO- $URL | grep -Po "/download/.*.tar.bz2" | sed s,^,$URL, | grep osx
```
failed.

**Comment by JoseOcasio** [comment]
I tried everything. I tried with Python3.8 and 2.7. I ended up just spinning an EC2 and had zero issues with a linux sandbox. Was able able to deploy a hello world. Will develop from there!

**Comment by d3m3vilurr** [comment]
@MaskedFuyu could you upload output of `curl https://github.com/vitasdk/autobuilds/releases`?

**Comment by ndlanier** [comment]
I also have this problem, I also made sure to set up a basic python alias pointing to python3.

```
==> Installing vitasdk to /usr/local/vitasdk
/usr/bin/curl
/home/ndlanier/vdpm/include/install-vitasdk.sh: line 4: python: command not found
http://: Invalid host name.

bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by ndlanier** [comment]
Ok the issue is python3 vs python. 

Update include/install-vitasdk.sh to the following on line 4:
`wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python3 - $@`

**Comment by JoseOcasio** [comment]
Yes. I ended up literally reseting python and python3 and have no issues. Also tested compiling in an ec2 instance (linux) and no issues.

**Comment by FibreFoX** [comment]
This issue seems to still persist, this is reproducable (for me) when using this `Dockerfile` (mostly to build on a windows-machine):
```dockerfile
FROM ubuntu:22.04

RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get -y install --no-install-recommends apt-utils dialog 2>&1
# stuff
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install git npm less iproute2 \
    build-essential \
    gcc g++ libtool cmake curl debconf-utils \
    git-core liblua5.1-0 \
    liblua5.1-0-dev libluabind-dev  \
    minizip make locales \
    nano unzip uuid-dev iputils-ping \
    zlib1g-dev zlib1g wget \
    gdb valgrind

# vita sdk 
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3 sudo autoconf texinfo bison flex

# vita SDK
ENV VITASDK=/usr/local/vitasdk
ENV PATH=$VITASDK/bin:$PATH
RUN cd /tmp \
    && git clone https://github.com/vitasdk/vdpm \
    && cd vdpm \
    && ./bootstrap-vitasdk.sh \
    && ./install-all.sh \
    && rm -rf /tmp/*
```

Even replacing "python" with "python3" (via sed) does not help.

Screenshot of the error message (mostly like the already reported one):
![grafik](https://user-images.githubusercontent.com/1042579/158271395-c8f812c7-8905-492d-b969-f6e5e88ce774.png)

Edit:

after adding `set -ex` to the `includes/install-vitasdk.sh` gives me this:
```
#19 0.272 Cloning into 'vdpm'...
#19 1.060 + '[' -d /usr/local/vitasdk ']'
#19 1.060 + echo '==> Installing vitasdk to /usr/local/vitasdk'
#19 1.060 + install_vitasdk /usr/local/vitasdk
#19 1.060 ==> Installing vitasdk to /usr/local/vitasdk
#19 1.060 + INSTALLDIR=/usr/local/vitasdk
#19 1.060 + case "$(uname -s)" in
#19 1.061 ++ uname -s
#19 1.062 + '[' -n '' ']'
#19 1.062 + command -v curl
#19 1.062 /usr/bin/curl
#19 1.062 + '[' '!' -d /usr/local/vitasdk ']'
#19 1.062 + sudo mkdir -p /usr/local/vitasdk
#19 1.074 ++ id -gn
#19 1.076 + sudo chown :root /usr/local/vitasdk
#19 1.086 + tar xj -C /usr/local/vitasdk --strip-components=1
#19 1.086 ++ get_download_link master linux
#19 1.087 ++ wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py
#19 1.087 ++ python - master linux
#19 1.087 /tmp/vdpm/include/install-vitasdk.sh: line 6: python: command not found
#19 1.304 + wget -O- ''
#19 1.307 http://: Invalid host name.
#19 1.307
#19 1.307 bzip2: Compressed file ends unexpectedly;
#19 1.307       perhaps it is corrupted?  *Possible* reason follows.
#19 1.307 bzip2: Inappropriate ioctl for device
#19 1.307       Input file = (stdin), output file = (stdout)
#19 1.307
#19 1.307 It is possible that the compressed file(s) have become corrupted.
#19 1.307 You can use the -tvv option to test integrity of such files.
#19 1.307
#19 1.307 You can use the `bzip2recover' program to attempt to recover
#19 1.307 data from undamaged sections of corrupted files.
#19 1.307
#19 1.308 tar: Child returned status 2
#19 1.308 tar: Error is not recoverable: exiting now
```

**Comment by FibreFoX** [comment]
In order to fix this, I tried to add some kind of python-detection.

Before:
```bash
get_download_link () {
  wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python - $@
}
```

After modification:
```bash
get_download_link () {
  wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | $(which python||which python3) - $@
}
```

It seems on some systems the correct path to the python-executable is needed (mostly due to /bin/sh being used internally instead of bash), so this should fix that (even help for python3 being used instead of python2)

Can someone try this?

**Comment by dgbrewer1989** [comment]
The solution by @FibreFoX works out for me. Windows 10 here.

**Comment by Engylizium** [comment]
Solution works but don't forget this line:
/Users/XXXX/vdpm/include/install-vitasdk.sh: line 6: python: command not found

**Comment by Engylizium** [comment]
It works but there's this:
/Users/USER/vdpm/include/install-vitasdk.sh: line 6: python: command not found

MacOS 12.6.1

**Comment by bgbofficial** [comment]
I use anaconda env, I try to solve it 

get_download_link () {
#  wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python - $@
}

**Comment by superfury** [comment]
Tried running bgbofficial's command in the latest MSYS2 I got installed.
It doesn't output anything at all?

Running on latest MSys2 updated on Windows 10 here (same issue on Windows 11).

bootstrap-vitasdk has the same http:// issue:
```
==> Installing vitasdk to /usr/local/vitasdk
Prepended http:// to ''
http://: Invalid host name.

bzip2.exe: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2.exe: No error
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
tar: Child returned status 2 of corrupted files.
tar: Error is not recoverable: exiting now
```

Running wget also gives nothing:
```
wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python3 - $@
```
Gives no output at all. Nothing even removing the piping to python3 gives nothing.

Changing the wget command inside install-vitasdk.sh to:
```
wget https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python3 - $@
```
Results in the following:
```
--2025-06-25 19:01:00--  https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py
Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt'
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
ERROR: The certificate of ‘github.com’ is not trusted.
ERROR: The certificate of ‘github.com’ doesn't have a known issuer.
Prepended http:// to ''
http://: Invalid host name.

bzip2.exe: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2.exe: No error
        Input file = (stdin), output file = (stdout)
tar: Child returned status 2
tar: Error is not recoverable: exiting now have become corrupted.
sh-5.2$ use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
```

**Comment by FibreFoX** [comment]
@superfury You are having a different problem.
```
ERROR: The certificate of ‘github.com’ is not trusted.
ERROR: The certificate of ‘github.com’ doesn't have a known issuer.
```

This means that your trust-store isn't accepting the HTTPS-certificate from github, most likely due to trust-store not being set up properly. You probably need to install the truststore on a fresh install: https://packages.msys2.org/packages/ca-certificates

**Comment by superfury** [comment]
@FibreFoX Installed said package with pacman. Ran update-ca-trust (it's only executable). No output. vitasdk-installer still can't reach github due to said certificate error.

Edit: Performed a full reinstall of MSys2, ran the usual update using pacman and my used libraries for Windows development, then proceeded to try and install using vdpm. Again, same errors. Nothing changed.
Edit: For now switched to WSL2(Ubuntu) for now. Although I need to use sudo to run sed for patching dependency (*.d) files created by gcc, which seems to require root privileges?

**Comment by frangarcj** [comment]
Closing this — since the 2026.08 release, `vdpm` doesn't go through `install-all.sh` / `install-vitasdk.sh` anymore. That whole thing (the per-package tarballs, the `/tmp/vdpm_install_*` bookkeeping) is gone; installs now go through a pacman-based client with signed channel manifests and per-package hash verification, so this exact failure shouldn't be possible anymore.

If you're setting up VitaSDK today, `./bootstrap-vitasdk.sh` replaces everything this issue is about. If you hit something similar with the current installer, open a fresh issue with the actual output and I'll take a look.

Thanks for reporting it back when it happened.
